export const errorModel = {
  statusCode: 200,
  errorDetails: "Details of the error (if any)",
  message: "Summary of the result",
};

export const userModel = {
  _id: "asd123asd-asd12asd",
  authId: "123d1d1c1c1c",
  paymentId: "s90df090d9s08s7g7809s",
  firstName: "John",
  lastName: "Doe",
  email: "example@email.com",
  profileImageUrl: "https://www.url.com",
  agreePrivacy: true,
  receiveCommunications: true,
  plan: 0,
};

export const planModel = {
  id: "prod_1234",
  default_price: "price_1234",
  description: "Pagefy Bla Subscription",
  features: {
    pt: ["Funcionalidade 1", "Funcionalidade 2"],
    en: ["Feature 1", "Feature 2"],
  },
  images: ["https://files.stripe.com/links/1234"],
  url: null,
  prices: [
    {
      id: "price_1234",
      object: "price",
      created_at: "2025-03-04T20:21:23.000Z",
      currency: "brl",
      lookup_key: "pagefy_sub_bla_month",
      nickname: null,
      product: "prod_1234",
      recurring: {
        aggregate_usage: null,
        interval: "month",
        interval_count: 1,
        meter: null,
        trial_period_days: null,
        usage_type: "licensed",
      },
      type: "recurring",
      unit_amount: 3990,
      unit_amount_decimal: "3990",
    },
  ],
  created_at: "2025-03-04T20:21:23.000Z",
  updated_at: "2025-03-04T20:33:32.000Z",
  name: "Boost",
};

export const checkoutModel = {
  id: "cs_1234",
  object: "checkout.session",
  adaptive_pricing: null,
  after_expiration: null,
  allow_promotion_codes: null,
  amount_subtotal: 3990,
  amount_total: 3990,
  automatic_tax: { enabled: false, liability: null, status: null },
  billing_address_collection: null,
  cancel_url: "https://example.me",
  client_reference_id: null,
  client_secret: null,
  collected_information: null,
  consent: null,
  consent_collection: null,
  created: 1741211151,
  currency: "brl",
  currency_conversion: null,
  custom_fields: [],
  custom_text: {
    after_submit: null,
    shipping_address: null,
    submit: null,
    terms_of_service_acceptance: null,
  },
  customer: null,
  customer_creation: "always",
  customer_details: null,
  customer_email: null,
  discounts: [],
  expires_at: 1741297551,
  invoice: null,
  invoice_creation: null,
  livemode: false,
  locale: null,
  metadata: {},
  mode: "subscription",
  payment_intent: null,
  payment_link: null,
  payment_method_collection: "always",
  payment_method_configuration_details: null,
  payment_method_options: { card: { request_three_d_secure: "automatic" } },
  payment_method_types: ["card"],
  payment_status: "unpaid",
  phone_number_collection: { enabled: false },
  recovered_from: null,
  saved_payment_method_options: {
    allow_redisplay_filters: ["always"],
    payment_method_remove: null,
    payment_method_save: null,
  },
  setup_intent: null,
  shipping_address_collection: null,
  shipping_cost: null,
  shipping_options: [],
  status: "open",
  submit_type: null,
  subscription: null,
  success_url: "https://example.me",
  total_details: { amount_discount: 0, amount_shipping: 0, amount_tax: 0 },
  ui_mode: "hosted",
  url: "https://checkout.stripe.com/c/pay/cs_1234",
};
